default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost

development:
  <<: *default
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>
  database: erb_test_development

test:
  <<: *default
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>
  database: erb_test_test

production:
  <<: *default
  host: ec2-54-225-121-235.compute-1.amazonaws.com
  database: d16t6nk3u99n98
  username: nhytbbmglssnhy
  password: 8e17f12ef0a542a619c98293f5f8765d922a65c9f9c6c7052b1a01e3c01b8208
  port: 5432
  url: postgres://nhytbbmglssnhy:8e17f12ef0a542a619c98293f5f8765d922a65c9f9c6c7052b1a01e3c01b8208@ec2-54-225-121-235.compute-1.amazonaws.com:5432/d16t6nk3u99n98

